tzid: America/Sao_Paulo
local:
  summary: Chá revelação (Rosa ou Luigi)
  dtstart: 20201108T180000Z
  dtend: 20201108T200000Z
  location: Rua dos parecis, 29, salão de festas
virtual:
  summary: Chá revelação (Rosa ou Luigi)
  dtstart: 20201108T193000Z
  dtend: 20201108T200000Z
  description: https://youtu.be/gchSYd324vU
youtube: https://youtu.be/gchSYd324vU
